name       : gpgme
version    : 1.18.0
release    : 24
source     :
    - https://gnupg.org/ftp/gcrypt/gpgme/gpgme-1.18.0.tar.bz2 : 361d4eae47ce925dba0ea569af40e7b52c645c4ae2e65e5621bf1b6cdd8b0e9e
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  :
    - security
    - ^python-gpg : programming.python
    - qt : security
    - qt-devel : programming.devel
summary    :
    - language library in C for cryptography support
    - ^python-gpg : A Python wrapper for the GPGME library
    - qt : Qt bindings for GPGME
    - qt-devel : Qt bindings for GPGME
description:
    - GPGME (GnuPG Made Easy) is a C language library that allows to add support for cryptography to a program. It is designed to make access to public key crypto engines like GnuPG or GpgSM easier for applications. GPGME provides a high-level crypto API for encryption, decryption, signing, signature verification and key management.
    - ^python-gpg : PyGPGME is a Python module that lets you sign, verify, encrypt and decrypt messages using the OpenPGP format.
    - qt : Qt bindings for GPGME, the library that allows to add support for cryptography to a program.
    - qt-devel : Qt bindings for GPGME, the library that allows to add support for cryptography to a program.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libassuan)
    - pkgconfig(python3)
    - gnupg
    - swig
rundeps    :
    - gnupg
    - qt-devel : gpgme-devel
patterns   :
    - ^python-gpg : /usr/lib/python*
    - qt : /usr/lib64/libqgpgme.so.*
    - qt-devel :
        - /usr/include/QGpgME
        - /usr/include/qgpgme
        - /usr/lib64/cmake/QGpgme
        - /usr/lib64/libqgpgme.so
environment: |
    export SETUPTOOLS_USE_DISTUTILS=local
    export SETUP_PY_EXTRA_OPTS="--single-version-externally-managed --root=/"
setup      : |
    %patch -Np1 < $pkgfiles/python310.patch
    %configure --disable-static --enable-languages=cpp,qt,python
build      : |
    %make
install    : |
    %make_install

    # Manually fix up python3 install path
    install -dm00644 $installdir/usr/lib/python%python3_version%/site-packages/gpg
    mv $installdir/usr/lib/python%python3_version%/site-packages/gpg-1.18.0-py%python3_version%-linux-x86_64.egg/EGG-INFO/ $installdir/usr/lib/python%python3_version%/site-packages/gpg
    mv $installdir/usr/lib/python%python3_version%/site-packages/gpg-1.18.0-py%python3_version%-linux-x86_64.egg/gpg/* $installdir/usr/lib/python%python3_version%/site-packages/gpg
    rm -fr $installdir/usr/lib/python%python3_version%/site-packages/gpg-1.18.0-py%python3_version%-linux-x86_64.egg/
#check      : |
#    %make check
