name        : gpgme
version     : 1.5.1
release     : 5
source      :
    - ftp://ftp.gnupg.org/gcrypt/gpgme/gpgme-1.5.1.tar.bz2 : 6c2f3af8ceeb303277d44ec0216d9a1271701f65b91d5942264cf7cefb4a11e3
license     : GPL-3.0
summary     : language library in C for cryptography support
component   : security
builddeps   :
    - gnupg
    - libassuan-devel
    - libgpg-error
description : |
    GPGME (GnuPG Made Easy) is a C language library that allows to add support for cryptography to a program. It is designed to make access to public key crypto engines like GnuPG or GpgSM easier for applications. GPGME provides a high-level crypto API for encryption, decryption, signing, signature verification and key management.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
