name       : gpgme
version    : 1.9.0
release    : 7
source     :
    - https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-1.9.0.tar.bz2 : 1b29fedb8bfad775e70eafac5b0590621683b2d9869db994568e6401f4034ceb
license    : GPL-3.0
summary    : language library in C for cryptography support
component  : security
builddeps  :
    - gnupg
    - libassuan-devel
    - libgpg-error
description: |
    GPGME (GnuPG Made Easy) is a C language library that allows to add support for cryptography to a program. It is designed to make access to public key crypto engines like GnuPG or GpgSM easier for applications. GPGME provides a high-level crypto API for encryption, decryption, signing, signature verification and key management.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
