name       : gpgme
version    : 1.13.1
release    : 14
source     :
    - https://github.com/gpg/gpgme/archive/gpgme-1.13.1.tar.gz : 5fb00f6b329932f474b458c1de56889bec85154c2c3e90a5f3fa90012823ebac
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  :
    - security
    - ^python-gpg : programming.python
    - qt : security
    - qt-devel : programming.devel
summary    :
    - language library in C for cryptography support
    - ^python-gpg : A Python wrapper for the GPGME library
    - qt : Qt bindings for GPGME
    - qt-devel : Qt bindings for GPGME
description:
    - GPGME (GnuPG Made Easy) is a C language library that allows to add support for cryptography to a program. It is designed to make access to public key crypto engines like GnuPG or GpgSM easier for applications. GPGME provides a high-level crypto API for encryption, decryption, signing, signature verification and key management.
    - ^python-gpg : PyGPGME is a Python module that lets you sign, verify, encrypt and decrypt messages using the OpenPGP format.
    - qt : Qt bindings for GPGME, the library that allows to add support for cryptography to a program.
    - qt-devel : Qt bindings for GPGME, the library that allows to add support for cryptography to a program.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(python3)
    - gnupg
    - libassuan-devel
    - swig
rundeps    :
    - gnupg
    - qt-devel : gpgme-devel
patterns   :
    - ^python-gpg : /usr/lib/python*
    - qt : /usr/lib64/libqgpgme.so.*
    - qt-devel :
        - /usr/include/QGpgME
        - /usr/include/qgpgme
        - /usr/lib64/cmake/QGpgme
        - /usr/lib64/libqgpgme.so
setup      : |
    %reconfigure --disable-static --enable-languages=cpp,qt,python
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
